In [1]:
# Importando a biblioteca do TensorFlow.
import tensorflow as tf

In [2]:
# Instanciando um tensor constante do tipo string.
hello = tf.constant("Hello, TensorFlow")

hello

<tf.Tensor: shape=(), dtype=string, numpy=b'Hello, TensorFlow'>

Operações Matemáticas com Tensores

Soma

In [3]:
# Instanciando tensores constantes zero-dimensionais (escalar) do tipo inteiro (padrão).
const_a = tf.constant(5)
const_b = tf.constant(9)

const_a, const_b

(<tf.Tensor: shape=(), dtype=int32, numpy=5>,
 <tf.Tensor: shape=(), dtype=int32, numpy=9>)

In [4]:
# Soma de tensores.
total = const_a + const_b

total

<tf.Tensor: shape=(), dtype=int32, numpy=14>

In [5]:
# Instanciação com passagem de tipo.
node_1 = tf.constant(5, dtype=tf.float32)
node_2 = tf.constant(9, dtype=tf.float32)

# Usando método de soma.
node_3 = tf.add(node_1, node_2)

node_3

<tf.Tensor: shape=(), dtype=float32, numpy=14.0>

Subtração

In [6]:
# Instanciando tensores unidimensionais (vetores) a partir de distribuições de probabilidade.
rand_a = tf.random.normal([3], 2.) # Três valores tomados de uma distribuição normal com média 2 e variância 1.
rand_b = tf.random.uniform([3], 1., 4.) # Três valores tomados de uma distribuição uniforme que vai de 1 a 4.

rand_a, rand_b

(<tf.Tensor: shape=(3,), dtype=float32, numpy=array([ 2.4147272 ,  4.7251425 , -0.63802624], dtype=float32)>,
 <tf.Tensor: shape=(3,), dtype=float32, numpy=array([3.3443322, 3.7615438, 2.8702345], dtype=float32)>)

In [7]:
# Método de subtração.
diff = tf.subtract(rand_a, rand_b)

diff

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([-0.929605 ,  0.9635987, -3.5082607], dtype=float32)>

Divisão

In [8]:
node_1 = tf.constant(21)
node_2 = tf.constant(7)

div = tf.math.truediv(node_1, node_2)

div

<tf.Tensor: shape=(), dtype=float64, numpy=3.0>

Multiplicação

In [9]:
# Instanciando tensores constantes bidimensionais (matrizes).
tensor_a = tf.constant([[4., 2.]])
tensor_b = tf.constant([[3.], [7.]])

tensor_a, tensor_b

(<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[4., 2.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
 array([[3.],
        [7.]], dtype=float32)>)

In [10]:
# Multiplicação element-wise.
prod = tf.math.multiply(tensor_a, tensor_b)

prod

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[12.,  6.],
       [28., 14.]], dtype=float32)>

In [11]:
mat_a = tf.constant([[2, 3], [9, 2], [4, 5]])
mat_b = tf.constant([[6, 4, 5], [3, 7, 2]])

mat_a, mat_b

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[2, 3],
        [9, 2],
        [4, 5]])>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[6, 4, 5],
        [3, 7, 2]])>)

In [12]:
# Multiplicação de matrizes.
mat_prod = tf.linalg.matmul(mat_a, mat_b)

mat_prod

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[21, 29, 16],
       [60, 50, 49],
       [39, 51, 30]])>

Variáveis

In [13]:
# Criando tensor variável.
changeable_tensor = tf.Variable([10, 7])

unchangeable_tensor = tf.constant([10, 7])

changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [14]:
# Tensores variáveis implementam o método de atribuição de valores.
changeable_tensor[0].assign(7)

changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7])>

In [15]:
# Já tensores constantes são imutáveis.
try:
    unchangeable_tensor[0].assign(7)
except AttributeError as err:
    print(err)

'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'


Tensores booleanos

In [16]:
# A construção de tensores booleanos segue a mesma sintaxe daquela usada na biblioteca numpy.
tf.ones(shape=(3, 1), dtype=tf.bool), tf.zeros(shape=(2, 5), dtype=tf.bool)

(<tf.Tensor: shape=(3, 1), dtype=bool, numpy=
 array([[ True],
        [ True],
        [ True]])>,
 <tf.Tensor: shape=(2, 5), dtype=bool, numpy=
 array([[False, False, False, False, False],
        [False, False, False, False, False]])>)